### ISSUE TITLE
Errors on go build

### ISSUE THREAD

**Issue by limlynn** [tumi8/QScanner#1]
Hello, Thank you for the great work on QUIC. I want to continue my research with your tool regarding QUIC. 

```
../go/pkg/mod/github.com/tumi8/quic-go@v0.21.3/noninternal/qtls/go118.go:3:1: expected 'package', found "quic-go doesn't build on Go 1.18 yet."
```

I got this message when I run `go build`. Is this because quic-go is not installed in my machine?
My go version is `go version go1.18 linux/amd64`

**Comment by sattler** [comment]
Hi, 
currently QScanner can be build with `go 1.16`. 

`go 1.18` is only out for three days and QScanner and all of its dependencies need to be updated. This might be done in future but we do not have a specific milestone planned.

Best regards,
Patrick
